### ISSUE TITLE
Add a warning to the README (due to this being, it seems at least, a userscript.)

### ISSUE THREAD

**Issue by embedvr** [Burntninjas/Acellus-Nord-Theme#2]
There have been cases of users being banned using a Userscript. Seems Acellus is able to detect if a user is running outside code. I would suggest a "use at your own risk" especially after the fairly recent student bans from using UserScripts.

**Comment by Burntninjas** [comment]
I forgot entirely that I had added that. I will make sure to remove it, as it's unrelated to the design in the first place.

**Comment by Burntninjas** [comment]
A disclaimer has been added. Further disclaimers are provided by the programs that may be used to inject the provided code.
